### ISSUE TITLE
Explicit type declarations is not handled!

### ISSUE THREAD

**Issue by Hubbitus** [php-kafka/php-avro-schema-generator#24]
Since [PHP 7.4 type declarations were introduced](https://www.php.net/manual/en/language.types.declarations.php).

But php-avro-schema-generator does not look in it.

Steps to reproduce:
```php
// in ../DAO/DemoNotification.php
class DemoNotification {
    private string $content;

    public function __construct(string $content) {
        $this->content = $content;
    }

    public function getContent(): string {
        return $this->content;
    }
}

$data = new DemoNotification("Hello");
$registry = (new ClassRegistry())
    ->addClassDirectory(__DIR__ . '/../DAO')
    ->load();
$generator = new SchemaGenerator($registry, '');
$schemas = $generator->generate();
echo(current($schemas)); // Out: {"type":"record","name":"DemoNotification","namespace":"App.DAO","fields":[{"name":"content","type":""}]}
```

## Actual behavior
Despite explicit type declaration:
```
private string $content;
```
Script outputs:
```json
{"type":"record","name":"DemoNotification","namespace":"App.DAO","fields":[{"name":"content","type":""}]}
```

## Expected behavior
```json
{"type":"record","name":"DemoNotification","namespace":"App.DAO","fields":[{"name":"content","type":"string"}]}
```

**Comment by nick-zh** [comment]
Heya, thanks for the report. Absolutely correct, i'll look into it :v:

**Comment by Hubbitus** [comment]
@nick-zh, please review pull-request addressing that issue https://github.com/php-kafka/php-avro-schema-generator/pull/25

**Comment by nick-zh** [comment]
Many thanks, i left some comments and also opened #26 for the next major, since i never liked that class to begin with :smile:

**Comment by Hubbitus** [comment]
Thank you very much! Could you please release a new version to do not hack that in my application?

**Comment by nick-zh** [comment]
Sure thing, i am on it, i need to fix the stan error, so i already merged your changes :v:
